/**
 * Service Content Importer
 * 
 * Imports service content from JSON files generated by browser-scraper.js
 * 
 * USAGE:
 * 
 * Option 1 - Import single service:
 *   node scripts/importServiceContent.js single service-data.json
 * 
 * Option 2 - Import multiple services:
 *   node scripts/importServiceContent.js bulk services-directory/
 * 
 * Option 3 - Import from stdin (paste JSON):
 *   node scripts/importServiceContent.js stdin
 */

require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs').promises;
const path = require('path');

const Service = require('../models/Service');
const ServiceSection = require('../models/ServiceSection');

/**
 * Import a single service
 */
async function importService(serviceData) {
  try {
    const { slug, name, sections, seo } = serviceData;

    // Find existing service
    const existingService = await Service.findOne({ slug });

    if (!existingService) {
      console.log(`⚠️  Service not found: ${slug}`);
      return { success: false, error: 'Service not found in database' };
    }

    console.log(`📝 Importing: ${name} (${slug})`);

    // Delete existing sections
    await ServiceSection.deleteMany({ serviceId: existingService._id });
    console.log(`   🗑️  Deleted old sections`);

    // Create new sections
    const sectionDocs = sections.map(section => ({
      serviceId: existingService._id,
      type: section.type,
      visible: section.visible,
      order: section.order,
      heading: section.heading,
      background: section.background,
      content: section.content
    }));

    await ServiceSection.insertMany(sectionDocs);
    console.log(`   ✅ Created ${sectionDocs.length} sections`);

    // Update SEO
    await Service.findByIdAndUpdate(existingService._id, {
      seo: {
        title: seo.title,
        metaDescription: seo.metaDescription
      }
    });
    console.log(`   ✅ Updated SEO`);

    return { success: true, sectionsCount: sectionDocs.length };

  } catch (error) {
    console.log(`   ❌ Error: ${error.message}`);
    return { success: false, error: error.message };
  }
}

/**
 * Import from single JSON file
 */
async function importSingleFile(filePath) {
  console.log(`\n📂 Reading file: ${filePath}\n`);
  
  const content = await fs.readFile(filePath, 'utf8');
  const serviceData = JSON.parse(content);
  
  return await importService(serviceData);
}

/**
 * Import from directory (bulk)
 */
async function importBulk(dirPath) {
  console.log(`\n📂 Reading directory: ${dirPath}\n`);
  
  const files = await fs.readdir(dirPath);
  const jsonFiles = files.filter(f => f.endsWith('.json'));
  
  console.log(`Found ${jsonFiles.length} JSON files\n`);
  
  const results = {
    total: jsonFiles.length,
    succeeded: 0,
    failed: 0,
    errors: []
  };

  for (let i = 0; i < jsonFiles.length; i++) {
    const file = jsonFiles[i];
    const filePath = path.join(dirPath, file);
    
    console.log(`\n[${i + 1}/${jsonFiles.length}] Processing: ${file}`);
    
    try {
      const content = await fs.readFile(filePath, 'utf8');
      const serviceData = JSON.parse(content);
      
      const result = await importService(serviceData);
      
      if (result.success) {
        results.succeeded++;
      } else {
        results.failed++;
        results.errors.push({ file, error: result.error });
      }
    } catch (error) {
      console.log(`   ❌ Error: ${error.message}`);
      results.failed++;
      results.errors.push({ file, error: error.message });
    }
  }

  return results;
}

/**
 * Import from stdin
 */
async function importFromStdin() {
  console.log('\n📋 Paste JSON data and press Ctrl+D (Unix) or Ctrl+Z (Windows) when done:\n');
  
  return new Promise((resolve, reject) => {
    let data = '';
    
    process.stdin.setEncoding('utf8');
    
    process.stdin.on('data', chunk => {
      data += chunk;
    });
    
    process.stdin.on('end', async () => {
      try {
        const serviceData = JSON.parse(data);
        const result = await importService(serviceData);
        resolve(result);
      } catch (error) {
        reject(error);
      }
    });
  });
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 Service Content Importer\n');
  console.log('='.repeat(50));

  const args = process.argv.slice(2);
  
  if (args.length === 0) {
    console.log('\nUsage:');
    console.log('  Single file:  node scripts/importServiceContent.js single <file.json>');
    console.log('  Bulk import:  node scripts/importServiceContent.js bulk <directory>');
    console.log('  From stdin:   node scripts/importServiceContent.js stdin');
    process.exit(1);
  }

  const mode = args[0];
  const target = args[1];

  // Connect to MongoDB
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');
  } catch (error) {
    console.error('❌ MongoDB connection failed:', error.message);
    process.exit(1);
  }

  try {
    let result;

    if (mode === 'single') {
      if (!target) {
        console.error('❌ Please provide a file path');
        process.exit(1);
      }
      result = await importSingleFile(target);
      
      if (result.success) {
        console.log('\n✅ Import successful!');
      } else {
        console.log('\n❌ Import failed');
      }
    } 
    else if (mode === 'bulk') {
      if (!target) {
        console.error('❌ Please provide a directory path');
        process.exit(1);
      }
      result = await importBulk(target);
      
      console.log('\n' + '='.repeat(50));
      console.log('\n📊 SUMMARY\n');
      console.log(`Total files: ${result.total}`);
      console.log(`✅ Succeeded: ${result.succeeded}`);
      console.log(`❌ Failed: ${result.failed}`);
      
      if (result.errors.length > 0) {
        console.log('\nErrors:');
        result.errors.forEach(({ file, error }) => {
          console.log(`  - ${file}: ${error}`);
        });
      }
    }
    else if (mode === 'stdin') {
      result = await importFromStdin();
      
      if (result.success) {
        console.log('\n✅ Import successful!');
      } else {
        console.log('\n❌ Import failed');
      }
    }
    else {
      console.error('❌ Invalid mode. Use: single, bulk, or stdin');
      process.exit(1);
    }

  } catch (error) {
    console.error('\n❌ Fatal error:', error.message);
    process.exit(1);
  }

  await mongoose.connection.close();
  console.log('\n✅ Done!\n');
  process.exit(0);
}

// Run
if (require.main === module) {
  main().catch(error => {
    console.error('\n❌ Fatal error:', error);
    process.exit(1);
  });
}

module.exports = { importService };
